version: "3"
services:
  flask:
    build:
      context: flask
      target: builder
    ports:
      - "5000:5000"
    restart: unless-stopped
    depends_on:
      - kafka
  zookeeper:
    image: docker.io/bitnami/zookeeper:3.9
    ports:
      - "2181:2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    volumes:
      - ./zookeeper:/bitnami/zookeeper
    restart: unless-stopped
  kafka:
    image: docker.io/bitnami/kafka:3.6
    ports:
      - "9093:9093"
    environment: 
      - KAFKA_BROKER_ID=1
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_LISTENERS=CLIENT://:9092,EXTERNAL://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=CLIENT://kafka:9092,EXTERNAL://localhost:9093
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=CLIENT
    volumes:
      - ./kafka:/bitnami/kafka
    depends_on:
      - zookeeper
  clickhouse:
    image: clickhouse/clickhouse-server:23.4.2.11
    container_name: langchain-clickhouse
    ports:
      - "8123:8123"
      - "9000:9000"
    volumes:
      - ./clickhouse/server/config.d:/etc/clickhouse-server/config.d
      - ./clickhouse/initdb.d:/docker-entrypoint-initdb.d
      - ./clickhouse/data:/var/lib/clickhouse
      - ./clickhouse/logs:/var/log/clickhouse-server
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    restart: unless-stopped